### ISSUE TITLE
Does not compile (neither beta nor nightly)

### ISSUE THREAD

**Issue by LukasKalbertodt** [rustless/rustless#38]
Compiling the complex example fails. I know, there are many problems with dependencies as well, but I this project hadn't had any activity for some time now. I hope rustless is still alive...

**Comment by s-panferov** [comment]
@LukasKalbertodt I'm waiting for https://github.com/chris-morgan/mopa/issues/1, but it looks abandoned. I think I have to refactor my projects to remove the dependency, it will take some time.

**Comment by LukasKalbertodt** [comment]
Removing dependencies sounds great in this current unstable Rust world... Thanks for working on it!

**Comment by allan-simon** [comment]
it seems now the issue you were linking on mopa is fixed, is there's still some other things to fix ? and is there any way to give a hand ?  because i think if it can compile with the beta of rust, then it will be a great step forward to make it "near-production" ready.

**Comment by LukasKalbertodt** [comment]
As far as I can tell, these are currently some issues:
- regex macros are used in rustless or some dependencies. Compiler extensions are unstable and not allowed in beta, therefore `regex` won't compile. I guess one needs to remove all uses of those macros.
- `phf_macros` is used in rustless or deps. Same as above.
- `jsonway` won't compile, but it seems like you already [fixed that](https://github.com/rustless/jsonway/pull/6)

**Comment by allan-simon** [comment]
yes actually after my message i suddenly got some free time so i started digging into that

interesting enough regex compile when i compile it alone (with beta2)

**Comment by LukasKalbertodt** [comment]
Yep, I already noticed that. Without using it's macros (I guess without `#![plugin(regex)]`), it works just fine. 
It would be really great if rustless is compiling again...

**Comment by allan-simon** [comment]
I've started to try to make valico compile (I'm going to eat something)
I haven't touched rust for a long time (6month) and I forgot , how can I tell valico to tell my patched version of jsonway ?

**Comment by s-panferov** [comment]
@LukasKalbertodt 	@allan-simon 	thanks for your work! Right now there are some troubles with deps such as `iron/body-parser` and some others. They must be fixed to compile rustless. I'm working on it.

**Comment by LukasKalbertodt** [comment]
By the way: Are you ( @s-panferov ) targeting beta or nightly or both? I think beta is more important... 
And if you could post a list of broken deps, we could try to fix some of them...

PS @allan-simon : I wrote an email to your address on your github profile... If you haven't seen yet.

**Comment by s-panferov** [comment]
@LukasKalbertodt right now I am trying to make it work on nightly because some deps now works only on nightly. Rustless itself is very conservative and doesn't use any unstable API, so after it will be fixed to work on nightly, we can adopt it for beta.

**Comment by s-panferov** [comment]
@allan-simon valico and jsonway has been already fixed on nightly. Now https://github.com/iron/body-parser/pull/55 is the blocker.

**Comment by LukasKalbertodt** [comment]
@s-panferov `body-parser` seems to be fixed now. Whats the status now?

**Comment by s-panferov** [comment]
Fixed

**Comment by LukasKalbertodt** [comment]
Nice!
However, "Fixed" may be misleading, because it still doesn't compile with beta. Maybe we should open another issue for beta. It should compile with beta before 1.0 is released I think...

**Comment by allan-simon** [comment]
yes good idea to have a ticket for beta.
